### ISSUE TITLE
geometry option not working

### ISSUE THREAD

**Issue by maxheld83** [rstudio/tufte#20]
I'm not 100% sure this is even an indented feature, but the [rmarkdown docs](http://rmarkdown.rstudio.com/pdf_document_format.html) seem to suggest it *is* possible to pass `\usepackage{geometry}` options to a document, like so:

```
---
title: "Crop Analysis Q3 2013"
output: pdf_document
fontsize: 11pt
geometry: margin=1in
---
```

However, when using this option with the `tufte::handout` template (the one right out of the RStudio 0.99.1281), the option appears not to work.

With this YAML, it's just ignored, and nothing changes:

```
---
title: "Tufte Handout"
author: "JJ Allaire and Yihui Xie"
date: '`r Sys.Date()`'
output:
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_html: default
link-citations: yes
subtitle: An implementation in R Markdown
bibliography: skeleton.bib
geometry: margin=15in
---
```

With this YAML, it errors out:

```
---
title: "Tufte Handout"
author: "JJ Allaire and Yihui Xie"
date: '`r Sys.Date()`'
output:
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
    geometry: margin=15in
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_html: default
link-citations: yes
subtitle: An implementation in R Markdown
bibliography: skeleton.bib
---
```

It would be really nice to change the paper format and use other geometry options.

Am I using it wrong or is this a limitation/bug?
