### ISSUE TITLE
tufte_handout and tufte_book messing the margin figure of the example

### ISSUE THREAD

**Issue by bnicenboim** [rstudio/tufte#22]
I recently installed tufte and rmarkdown with devtools (I'm not using Rstudio).
I created an example using draft("notes.Rmd", template = "tufte_html", package = "tufte")

The html works perfect, I wanted to create a pdf, and I modified the header to this:
```
---
title: "Tufte Handout"
subtitle: "An implementation in R Markdown"
author: "JJ Allaire and Yihui Xie"
date: "`r Sys.Date()`"
output:
  tufte::tufte_handout: 
    citation_package: natbib
    latex_engine: xelatex
    keep_tex: true
  tufte::tufte_html: default
  tufte::tufte_book: 
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---
```

But the pdf has the image with the caption "MPG vs horsepower, colored by transmission]{MPG vs horse-power, colored by transmission" pretty messed up: it doesn't appear in the margin, and the pdf prints part of the latex code. I peaked at the latex code and I found stuff like this:

```
\textbackslash{}begin\{marginfigure\}
\includegraphics{ADA_notes_files/figure-latex/fig-margin-1}
\textbackslash{}caption{[}MPG vs horsepower, colored by
transmission{]}\{MPG vs horsepower, colored by
transmission.\}\label{fig:fig-margin}
\textbackslash{}end\{marginfigure\}

```
I'm also attaching the tex file here as txt: [notes.txt](https://github.com/rstudio/tufte/files/502793/notes.txt)

Is there some workaround?  Or it could be because of a problem between the versions?

my sessionInfo() looks like this:
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.04

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.14         slidify_0.4.5      rmarkdown_1.0.9016 tufte_0.2.2       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7     digest_0.6.8    withr_1.0.2     assertthat_0.1 
 [5] R6_2.1.1        git2r_0.11.0    magrittr_1.5    evaluate_0.9   
 [9] httr_1.0.0      stringi_1.1.1   curl_0.9.3      whisker_0.3-2  
[13] devtools_1.12.0 tools_3.2.3     stringr_1.1.0   markdown_0.7.7 
[17] yaml_2.1.13     memoise_1.0.0   htmltools_0.3.5 tibble_1.2     
> 
```

(Unrelated to all this, you guys are doing pretty cool stuff! Every single time I start to use something new, I discover that the author is either Yihui Xie or Hadley Wickham)
