### ISSUE TITLE
multiple authors

### ISSUE THREAD

**Issue by zeigerpuppy** [rstudio/tufte#43]
When I try to include two authors in the YAML header and build, I get the following error.
Is there a way to include multiple authors?

YAML
```yaml
---
title: Title of submission
author:
  - Author One
  - Author Two
date: "`r format(Sys.time(), '%d %B %Y')`"
bibliography: mybibfile.bib
output:
  tufte::tufte_handout: default
  tufte::tufte_html: default
  rticles::plos_article: default
csl: plos.csl
---
```

build command:
```
rmarkdown::render("Article.Rmd", tufte::tufte_handout(), output_dir="_out_tufte")
```

error:
```
! Extra \fi.
<argument> ...rrenvir \else \@badend {tabular}\fi
                                                  \expandafter \endgroup \if...
l.65 \author{Author One \and Author Two}
```
