### ISSUE TITLE
Unable to change engine to xelatex with tufte-handout

### ISSUE THREAD

**Issue by zeigerpuppy** [rstudio/tufte#47]
I am trying to change the rendering engine to xelatex because I have some unicode characters in my Rmarkdown file that pdflatex throws an error on

```
/usr/bin/pandoc +RTS -K512m -RTS Protocol.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /projects/PROTOCOL/Description/_out_tufte_pdf/Protocol.pdf --table-of-contents --toc-depth 2 --template /usr/local/lib/R/site-library/tufte/rmarkdown/templates/tufte_handout/resources/tufte-handout.tex --hi
ghlight-style pygments --latex-engine pdflatex --variable 'documentclass:tufte-handout' --bibliography mybibfile.bib --filter /usr/bin/pandoc-citeproc
! Package inputenc Error: Unicode char μ (U+3BC)
(inputenc)                not set up for use with LaTeX.
 
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...
 
l.343 ...cy, corresponding to the rate of rise (μ
 
Try running pandoc with --latex-engine=xelatex.
pandoc: Error producing PDF
Error: pandoc document conversion failed with error 43
Execution halted
```

I have tried a few different methods but the `--latex-engine pdflatex` keeps being selected.
My YAML header is the following:

```yaml
---
title: Protocol
author:
- FRM
date: "`r format(Sys.time(), '%d %B %Y')`"
bibliography: mybibfile.bib
link-citations: yes
header-includes:
   - \usepackage{fontenc}
output:
  tufte::tufte_handout:
    fig_width: 6
    fig_height: 4.5
    keep_tex: true
    latex_engine: xelatex
    toc: true
    pandoc_args: [
      "--latex-engine=xelatex"
    ]
    includes:
#      in_header: preamble.tex
#      before_body: doc_prefix.tex
#      after_body: doc_suffix.tex
  tufte::tufte_html: default
  rticles::plos_article: default
  word_document:
    fig_width: 5
    fig_height: 5
    fig_caption: true
csl: plos.csl
abstract: "(Abstract: to be expanded)"
---
```

as you see, I've also tried passing pandoc arguments

The build file looks like this (I'm building in HTML/word/PDF in the same build)

```R
#!/usr/bin/Rscript
# this script builds our article.

require(knitr)
require(rmarkdown)
require(rticles)
require(tufte)

setwd("~/PROTOCOL/Description/") 

# build in article format: plos
# nb: marginnotes don't work in this format!
# rmarkdown::render("Article.Rmd", rticles::plos_article(), output_dir="_out_pdf")

# build word format
rmarkdown::render("Protocol.Rmd", output_format = "word_document", output_dir="_out_word")
# see
# http://rmarkdown.rstudio.com/articles_docx.html


# build in tufte format
# NB: multiple authors are not supported in this format
# see 
# - http://rmarkdown.rstudio.com/tufte_handout_format.html
# - http://rstudio.github.io/tufte/
rmarkdown::render("Protocol.Rmd", tufte::tufte_handout(toc = TRUE), output_dir="_out_tufte_pdf")
rmarkdown::render("Protocol.Rmd", tufte::tufte_html(), output_dir="_out_tufte_html")
```

Am I missing some way to force building with xelatex?

**Comment by zeigerpuppy** [comment]
As a note to anyone also having this problem,
I have temporarily worked around it by pulling in a preamble using this is the YAML header.
It's still using `pdflatex` but at least the greek characters work...

```YAML
header-includes:
    - \input{preamble.tex}
```

and preamble.tex

```
% set font encoding for PDFLaTeX or XeLaTeX
\usepackage{ifxetex}
\ifxetex
  \usepackage{fontspec}
\else
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{lmodern}
  \usepackage[greek,english]{babel}
  \usepackage{textgreek}
\fi
```

**Comment by yihui** [comment]
Use

```r
rmarkdown::render("Protocol.Rmd", "tufte::tufte_handout")
```

instead of

```r
rmarkdown::render("Protocol.Rmd", tufte::tufte_handout(toc = TRUE))
```

And setting `latex_engine` is enough:

```yaml
output:
  tufte::tufte_handout:
    latex_engine: xelatex
```

There is no need to use `pandoc_args`.

The reason that you got `pdflatex` all the time because you called the _function_ `tufte::tufte_handout()` to return the output format (which overrides your YAML settings), and the default value for `latex_engine` is `pdflatex` in the _function_.

FWIW, I used `xelatex` in the default template in this package, so `xelatex` definitely should work:
https://github.com/rstudio/tufte/blame/master/inst/rmarkdown/templates/tufte_html/skeleton/skeleton.Rmd#L10

BTW, I can only handle Github issues for bug reports and feature requests, and usually I don't have time to answer general questions. Please [ask future questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead, so you won't have to wait for me. Thanks!
