### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by ds221** [rstudio/tufte#68]
Hello

my _site.yml file is:

```
name: "Level 3 benchmarking"
type: inverse
navbar:
  left:
    - text: "Findings"
      href: index.html
    - text: "Numbers and Age Groups"
      href: numbers.html
    - text: "Entry and outcomes"
      href: entry.html
    - text: "Cost"
      href: cost.html
    - text: "Promotion"
      href: promotion.html
  
output_dir: "benchmarking"
```

and each Rmd file starts with:

```
title: "Bikeability Level 3 benchmarking survey"
output:
  tufte::tufte_html:
    tufte_features: ["fonts", "background", "italics"]
    tufte_variant: default
```

The navbar does not show. If I change the output back to html_document it does show

---

By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.name/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tufte')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/tufte')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.
