### ISSUE TITLE
floating TOC in tufte book

### ISSUE THREAD

**Issue by chipbrock** [rstudio/tufte#72]
This is a question and issue that has not received an answer on Stackoverflow after a day. 
[floating TOC in tufte book](https://stackoverflow.com/questions/57846247/floating-toc-in-tufte-book)

Since I posted it I've confirmed it in another approach to standing up a stock tufte book. I believe this is real, although I confess that I'm still learning.

Here is a few-line modification to the index.Rmd file for the demo:

```
--- 
title: "A Minimal Book Example"
author: "Yihui Xie"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  tufte::tufte_html: default
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
  bookdown::tufte_html_book:
    toc: true
    toc_float: true
    css: toc.css
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format f
```
Inclusion of toc: true works. The **top_float: true** insertion results in the error:

```
Error in rmarkdown::html_document(..., extra_dependencies = c(extra_dependencies,  : 
  You must use a theme when specifying the 'toc_float' option
Calls: <Anonymous> ... html_chapters -> base_format -> html_document2 -> <Anonymous>
Execution halted

Exited with status 1.
```
This happens with the toc lines where they are shown and also as an argument to the tufte::tufte_html: line.

I don't see that the need to include a theme is included in the toc section in the "Definitive Guide" book. In any case, addition of a theme in what I think is the normal way doesn't help.  I'd appreciate some help. 

I have written and am currently using a variation of tufte format starting from (the award-winning!)  [programmingforpsych](https://github.com/CrumpLab/programmingforpsych/blob/master/index.Rmd) but I think I'd prefer to stick with the standard tufte package. But only if I can include the floating toc.

Thanks in advance for your help.

---

By filing an issue to this repo, I promise that

- [ x] I have fully read the issue guide at https://yihui.name/issue/.
- [ x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tufte')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/tufte')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.
